import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/complete.module.css";
import { Reservation } from "../../types/Reservation";


const ReservationComplete: NextPage = () => {

  const toJsonStorage = (storage: string | null): string => {
    if (storage !== null) {
      return JSON.parse(storage);
    }
    return "";
  };

  const storage  = toJsonStorage(localStorage.getItem("reservation")) as Reservation;
  const seatName = toJsonStorage(localStorage.getItem("seatName"));
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>予約が完了しました。</h1>

        <div className={styles.items}>
          <div>
            <div>
              <label>支払番号</label>
              <span className={styles.paymentCode}>ECM271605</span>
            </div>
            <div>
              <label>映画館</label>
              <span>{storage.theaterName}</span>
            </div>
            <div>
              <label>作品</label>
              <span>{storage.filmName}</span>
            </div>
            <div>
              <label>上映日時</label>
              <span>{storage.schedule}</span>
            </div>
            <div>
              <label>座席</label>
              <span>{seatName}</span>
            </div>
            {/* <div>
              <label>券の種類</label>
              <span>大人(20歳以上) 1枚</span>
            </div>
            <div>
              <label>お支払方法</label>
              <span>後から決済</span>
            </div>
            <div>
              <label>金額</label>
              <span>¥ 1,800</span>
            </div> */}
          </div>
        </div>
      </main>
    </div>
  );
};

export default ReservationComplete;
