import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/complete.module.css";

import {Reservation} from "../../types/Reservation";

const ReservationConfirm: NextPage = () => {
  const router = useRouter();

  const reservation :Reservation = {
    theaterName : '',
    filmName  : '',
    schedule : '',
    count : '',
    ticketType : '',
    seatName : '',
    money : '',
    paymentMethod : '', 
  }



  const clickConfirm = () => {

    
  localStorage.setItem('reservation', JSON.stringify(reservation));
  console.log(localStorage);

//   localStorage.setItem("reservation.filmName", "panda");
//   console.log(localStorage);

    router.push({
        pathname:"complete",   //URL
        // query: {reservation :reservation}
        query: {    
            paymentCode : 'ECM271605',
            theaterName : 'イオンシネマ　みなとみらい',
        filmName  : '劇場版　呪術廻戦０',
        schedule : '2/7（月）16：05～18：00',
        count : '1枚',
        ticketType : '大人(20歳以上)',
        seatName : 'J-17',
        money : '¥ 1,800',
        paymentMethod : '後から決済',
    }});
  }


  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>予約が完了しました。</h1>

        <div className={styles.items}>
          <div>
            <div>映画館</div>
            <div>作品</div>
            <div>上映日時</div>
            <div>座席</div>
            <div>券の種類</div>
            <div>お支払方法</div>
            <div>金額</div>
          </div>
          <div>
            <div>イオンシネマ　みなとみらい</div>
            <div>劇場版　呪術廻戦０</div>
            <div>2/7（月）16：05～18：00</div>
            <div>J-17</div>
            <div>大人(20歳以上)　 1枚</div>
            <div>後から決済</div>
            <div>¥ 1,800</div>
          </div>
        </div>
        <div>
            <button onClick={clickConfirm}></button>
        </div>
      </main>
    </div>
  );
};

export default ReservationConfirm;
